### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by ddieppa** [madskristensen/WebExtensionPack2017#3]
### Installed product versions
- Visual Studio:  Microsoft Visual Studio Enterprise 2017 RC
- Extension: Web Extension Pack 2017 version 1.1.5

### Description
Just download the extension withing visual studio and didn't install

### Steps to recreate
1. Download extension
2. close Visual Studio 
3. the installation will fail

### Current behavior
Here is the error log:

12/12/2016 4:18:54 PM - Microsoft VSIX Installer
12/12/2016 4:18:54 PM - -------------------------------------------
12/12/2016 4:18:54 PM - vsixinstaller.exe version:
12/12/2016 4:18:54 PM - 15.0.26009.0 built by: D15REL
12/12/2016 4:18:54 PM - -------------------------------------------
12/12/2016 4:18:54 PM - Command line parameters:
12/12/2016 4:18:54 PM - C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\vsixinstaller.exe,/appidinstallpath:C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\devenv.exe,/skuName:Enterprise,/skuVersion:15.0.26009.0,/appidname:Microsoft Visual Studio Enterprise 2017 RC,C:\Users\ddieppa\AppData\Local\Temp\VSIXxz1t2hy3.vsix
12/12/2016 4:18:54 PM - -------------------------------------------
12/12/2016 4:18:54 PM - Microsoft VSIX Installer
12/12/2016 4:18:54 PM - -------------------------------------------
12/12/2016 4:18:55 PM - Initializing Install...
12/12/2016 4:18:55 PM - Extension Details...
12/12/2016 4:18:55 PM - 	Identifier         : bb7e2273-9a70-4e5e-b4dd-1f361b6166c0
12/12/2016 4:18:55 PM - 	Name               : Web Extension Pack 2017
12/12/2016 4:18:55 PM - 	Author             : Mads Kristensen
12/12/2016 4:18:55 PM - 	Version            : 1.1.5
12/12/2016 4:18:55 PM - 	Description        : The easiest way to set up Visual Studio for the ultimate web development experience.
12/12/2016 4:18:55 PM - 	Locale             : en-US
12/12/2016 4:18:55 PM - 	MoreInfoURL        : https://visualstudiogallery.msdn.microsoft.com/f3b504c6-0095-42f1-a989-51d5fc2a8459
12/12/2016 4:18:55 PM - 	InstalledByMSI     : False
12/12/2016 4:18:55 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
12/12/2016 4:18:55 PM - 
12/12/2016 4:18:55 PM - 	SignatureState     : Unsigned
12/12/2016 4:18:55 PM - 	Supported Products : 
12/12/2016 4:18:55 PM - 		Microsoft.VisualStudio.Community
12/12/2016 4:18:55 PM - 			Version : [15.0]
12/12/2016 4:18:55 PM - 
12/12/2016 4:18:55 PM - 	References         : 
12/12/2016 4:18:55 PM - 	Prerequisites      : 
12/12/2016 4:18:55 PM - 		-------------------------------------------------------
12/12/2016 4:18:55 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
12/12/2016 4:18:55 PM - 		Name         : Visual Studio core editor
12/12/2016 4:18:55 PM - 		Version      : [15.0,16.0)
12/12/2016 4:18:55 PM - 
12/12/2016 4:18:55 PM - 		-------------------------------------------------------
12/12/2016 4:18:55 PM - 		Identifier   : Microsoft.VisualStudio.Component.Web
12/12/2016 4:18:55 PM - 		Name         : Web development tools
12/12/2016 4:18:55 PM - 		Version      : [15.0,16.0)
12/12/2016 4:18:55 PM - 
12/12/2016 4:18:55 PM - Signature Details...
12/12/2016 4:18:55 PM - 	Extension is not signed.
12/12/2016 4:18:55 PM - 
12/12/2016 4:18:58 PM - The extension with ID 'bb7e2273-9a70-4e5e-b4dd-1f361b6166c0' is not installed to Microsoft Visual Studio Enterprise 2017 RC.
12/12/2016 4:19:58 PM - The following target products have been selected...
12/12/2016 4:19:58 PM - 	Microsoft Visual Studio Enterprise 2017 RC
12/12/2016 4:19:58 PM - 
12/12/2016 4:20:01 PM - Beginning to install extension to Microsoft Visual Studio Enterprise 2017 RC...
12/12/2016 4:20:02 PM - Install Error : System.IO.FileNotFoundException: Unable to find the specified file.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.GetCurrentSetupInstance()
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

.

**Comment by madpeanut** [comment]
I'm having a similar issue.  I have VS 2017 RC Enterprise here is what I get:
1/22/2017 9:56:33 PM - Microsoft VSIX Installer
1/22/2017 9:56:33 PM - -------------------------------------------
1/22/2017 9:56:33 PM - vsixinstaller.exe version:
1/22/2017 9:56:33 PM - 15.0.26020.0 built by: D15REL
1/22/2017 9:56:33 PM - -------------------------------------------
1/22/2017 9:56:33 PM - Command line parameters:
1/22/2017 9:56:33 PM - E:\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VSIXInstaller.exe,C:\Users\Matt\AppData\Local\Microsoft\Windows\INetCache\IE\H1Q2PXXF\Web Extension Pack 2017 v1.2.7.vsix
1/22/2017 9:56:33 PM - -------------------------------------------
1/22/2017 9:56:33 PM - Microsoft VSIX Installer
1/22/2017 9:56:33 PM - -------------------------------------------
1/22/2017 9:56:33 PM - Initializing Install...
1/22/2017 9:56:33 PM - Extension Details...
1/22/2017 9:56:33 PM - 	Identifier         : bb7e2273-9a70-4e5e-b4dd-1f361b6166c0
1/22/2017 9:56:33 PM - 	Name               : Web Extension Pack 2017
1/22/2017 9:56:33 PM - 	Author             : Mads Kristensen
1/22/2017 9:56:33 PM - 	Version            : 1.2.7
1/22/2017 9:56:33 PM - 	Description        : The easiest way to set up Visual Studio for the ultimate web development experience.
1/22/2017 9:56:33 PM - 	Locale             : en-US
1/22/2017 9:56:33 PM - 	MoreInfoURL        : https://visualstudiogallery.msdn.microsoft.com/f3b504c6-0095-42f1-a989-51d5fc2a8459
1/22/2017 9:56:33 PM - 	InstalledByMSI     : False
1/22/2017 9:56:33 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
1/22/2017 9:56:33 PM - 
1/22/2017 9:56:33 PM - 	SignatureState     : Unsigned
1/22/2017 9:56:33 PM - 	Supported Products : 
1/22/2017 9:56:33 PM - 		Microsoft.VisualStudio.Community
1/22/2017 9:56:33 PM - 			Version : [15.0]
1/22/2017 9:56:33 PM - 
1/22/2017 9:56:33 PM - 	References         : 
1/22/2017 9:56:33 PM - 	Prerequisites      : 
1/22/2017 9:56:33 PM - 		-------------------------------------------------------
1/22/2017 9:56:33 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
1/22/2017 9:56:33 PM - 		Name         : Visual Studio core editor
1/22/2017 9:56:33 PM - 		Version      : [15.0,16.0)
1/22/2017 9:56:33 PM - 
1/22/2017 9:56:33 PM - 		-------------------------------------------------------
1/22/2017 9:56:33 PM - 		Identifier   : Microsoft.VisualStudio.Component.Web
1/22/2017 9:56:33 PM - 		Name         : Web development tools
1/22/2017 9:56:33 PM - 		Version      : [15.0,16.0)
1/22/2017 9:56:33 PM - 
1/22/2017 9:56:33 PM - Signature Details...
1/22/2017 9:56:33 PM - 	Extension is not signed.
1/22/2017 9:56:33 PM - 
1/22/2017 9:56:33 PM - Searching for applicable products...
1/22/2017 9:56:33 PM - Found installed product - Global Location
1/22/2017 9:56:34 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
